MemosTimetabling: Udine::SolutionPolishingStrategyI Class Reference
Udine::SolutionPolishingStrategyI Class Reference
#include <strategy.h>
Public Member Functions
SolutionPolishingStrategyI (IloEnv &environment, Model &s, Config &configuration)
virtual void main ()
virtual void finishOff ()
Protected Attributes
Neighbourhoods fixPeriodNeighbs
Detailed Description
Definition at line 114 of file strategy.h.
Constructor & Destructor Documentation
Udine::SolutionPolishingStrategyI::SolutionPolishingStrategyI (IloEnv & environment, Model & s, Config & configuration) [inline]
Definition at line 119 of file strategy.h.
  : StrategyI(environment, s, configuration) {
  }
Member Function Documentation
void SolutionPolishingStrategyI::finishOff () [virtual]
Implements Udine::StrategyI.
Definition at line 410 of file strategy.cpp.
References Udine::StrategyI::config, Udine::FixPeriodDiveFromFixDay, fixPeriodNeighbs, Udine::Config::getCount(), and Udine::StrategyI::runDiver().
{
  int counter = 0;
  while (   !fixPeriodNeighbs.empty()
         && counter < config.getCount(FixPeriodDiveFromFixDay)) {
    runDiver(fixPeriodNeighbs.back());
    fixPeriodNeighbs.pop_back();
    counter += 1;
  }
}
void SolutionPolishingStrategyI::main () [virtual]
Implements Udine::StrategyI.
Definition at line 405 of file strategy.cpp.
References Udine::Config::addSolutionCost(), Udine::StrategyI::config, Udine::Model::definition, fixPeriodNeighbs, Udine::StrategyI::getFixPeriodNeighbourhood(), Udine::StrategyI::model, and Udine::Neighbourhood::type.
{
  config.addSolutionCost(model.definition.type, getObjValue());
  fixPeriodNeighbs.push_back(getFixPeriodNeighbourhood());
}
Field Documentation
Neighbourhoods Udine::SolutionPolishingStrategyI::fixPeriodNeighbs [protected]
Definition at line 116 of file strategy.h.
Referenced by finishOff(), and main().
The documentation for this class was generated from the following files:
src/strategy.h
src/strategy.cpp