MemosTimetabling: Udine::StrategyI Class Reference
Udine::StrategyI Class Reference
#include <strategy.h>
Public Member Functions
StrategyI (IloEnv &environment, Model &s, Config &configuration)
virtual int sumMissingCourseDays ()
virtual int sumSingletonChecks ()
virtual int sumMissingSeats ()
virtual int sumExtraRoomsUsed ()
virtual void logNeighbrouhood (Neighbourhood def)
virtual Neighbourhood getFixDayNeighbourhood ()
virtual Neighbourhood getFixPeriodNeighbourhood ()
virtual void runDiver (Neighbourhood definition)
virtual void main ()=0
virtual void finishOff ()=0
Protected Attributes
IloEnv env
Config & config
Model & model
Detailed Description
Definition at line 41 of file strategy.h.
Constructor & Destructor Documentation
Udine::StrategyI::StrategyI (IloEnv & environment, Model & s, Config & configuration) [inline]
Definition at line 50 of file strategy.h.
  : IloCplex::IncumbentCallbackI(environment), env(environment), model(s), config(configuration) {}
Member Function Documentation
virtual void Udine::StrategyI::finishOff () [pure virtual]
Implemented in Udine::AnytimeStrategyI, Udine::ContractStrategyI, Udine::SolutionSavingStrategyI, and Udine::SolutionPolishingStrategyI.
Referenced by runDiver(), and Udine::Solver::Solver().
Neighbourhood StrategyI::getFixDayNeighbourhood () [virtual]
Definition at line 170 of file strategy.cpp.
References Udine::Neighbourhood::cost, Udine::CourseDayNumberTriple::course, Udine::CoursePeriodPair::course, Udine::CourseDayNumberTriple::day, Udine::Model::definition, env, Udine::CourseDayNumberTriple::events, Udine::Neighbourhood::fixDay, Udine::FixDay, Udine::Instance::getCourseCount(), Udine::Instance::getDayCount(), Udine::Instance::getPeriodsPerDayCount(), Udine::Instance::getRoomCount(), Udine::Model::instance, Udine::Neighbourhood::lowerBound, model, Udine::Neighbourhood::penaltyCompactness, Udine::Neighbourhood::penaltyMinCourseDays, Udine::CoursePeriodPair::period, Udine::Neighbourhood::preprocessAway, roundProperly(), sumMissingCourseDays(), sumSingletonChecks(), Udine::Neighbourhood::type, Udine::Model::vars, and Udine::Variables::x.
Referenced by Udine::ContractStrategyI::main(), and Udine::AnytimeStrategyI::main().
{
  Neighbourhood next;
  next.type = FixDay;
  next.cost = getObjValue();
  next.lowerBound = getBestObjValue();
  next.penaltyMinCourseDays = sumMissingCourseDays();
  next.penaltyCompactness = sumSingletonChecks();
  int c, d, p, r;  // course, day, period, room
  for(c = 0; c < model.instance.getCourseCount(); c++) {
    CoursePeriodPair pair;
    pair.course = c;
    CourseDayNumberTriple triple;
    triple.course = c;
    for (d = 0; d < model.instance.getDayCount(); d++) {
      triple.day = d;
      triple.events = 0;
      bool ok = true;
      for (p = d * model.instance.getPeriodsPerDayCount();
           p < (d + 1) * model.instance.getPeriodsPerDayCount(); p++)
        try {
          IloExpr sum(env);
          for (r = 0; r < model.instance.getRoomCount(model.definition.type); r++)
            sum += model.vars.x[p][r][c];
          triple.events += roundProperly(getValue(sum));
        } catch (IloAlgorithm::NotExtractedException e)  {
          std::cerr << "Error retrieving value of x for c = " << c << " and d = " << d << "." << std::endl;
          ok = false;
        } catch (...) {
          std::cerr << "Unknown error retrieving value of x for c = " << c << " and d = " << d << "." << std::endl;
          throw;
        }
      if (triple.events > 0) {
        next.fixDay.push_back(triple);
      } else if (ok)
        for (p = d * model.instance.getPeriodsPerDayCount();
             p < (d + 1) * model.instance.getPeriodsPerDayCount();
             p++) {
        pair.period = p;
        next.preprocessAway.push_back(pair);
      }
    }
  }
  return next;
}
Neighbourhood StrategyI::getFixPeriodNeighbourhood () [virtual]
Definition at line 134 of file strategy.cpp.
References Udine::Neighbourhood::cost, Udine::CoursePeriodPair::course, Udine::Variables::coursePeriods, Udine::Model::definition, env, Udine::FixDay, Udine::Neighbourhood::fixPeriod, Udine::FixPeriod, Udine::Instance::getCourseCount(), Udine::Instance::getPeriodCount(), Udine::Instance::getRoomCount(), Udine::Model::instance, Udine::Neighbourhood::lowerBound, model, Udine::Neighbourhood::penaltyCompactness, Udine::Neighbourhood::penaltyMinCourseDays, Udine::CoursePeriodPair::period, Udine::Neighbourhood::preprocessAway, roundProperly(), sumMissingCourseDays(), sumSingletonChecks(), Udine::Neighbourhood::type, Udine::Model::vars, and Udine::Variables::x.
Referenced by Udine::SolutionPolishingStrategyI::main(), Udine::ContractStrategyI::main(), and Udine::AnytimeStrategyI::main().
{
  Neighbourhood next;
  next.type = FixPeriod;
  next.cost = getObjValue();
  next.lowerBound = getBestObjValue();
  next.penaltyMinCourseDays = sumMissingCourseDays();
  next.penaltyCompactness = sumSingletonChecks();
  int c, p, r;  // course, period
  for(c = 0; c < model.instance.getCourseCount(); c++)
    for (p = 0; p < model.instance.getPeriodCount(); p++) {
      CoursePeriodPair pair;
      pair.period = p;
      pair.course = c;
      try {
        IloExpr sum(env);
        for (r = 0; r < model.instance.getRoomCount(model.definition.type); r++)
          sum += model.vars.x[p][r][c];
        assert(std::fabs(1 - getValue(sum)) < 0.0001 || std::fabs(getValue(sum)) < 0.0001);
        if (roundProperly(getValue(sum)) == 1)
          next.fixPeriod.push_back(pair);
        else
          next.preprocessAway.push_back(pair);
        if (model.definition.type == FixDay)
          assert(roundProperly(getValue(sum)) == roundProperly(getValue(model.vars.coursePeriods[c][p])));
      } catch (IloAlgorithm::NotExtractedException e)  {
        std::cerr << "Error retrieving " << model.vars.x[p][r][c].getName() << "." << std::endl;
      } catch (...)  {
        std::cerr << "Unknown error retrieving " << model.vars.x[p][r][c].getName() << "." << std::endl;
        throw;
      }
    }
  return next;
}
void StrategyI::logNeighbrouhood (Neighbourhood def) [virtual]
Definition at line 91 of file strategy.cpp.
References Udine::Model::config, config, Udine::Neighbourhood::cost, Udine::Config::elapsed(), env, Udine::Neighbourhood::fixDay, Udine::Neighbourhood::fixPeriod, Udine::Config::getParam(), Udine::Neighbourhood::lowerBound, model, Udine::Config::path, Udine::Neighbourhood::penaltyCompactness, Udine::Neighbourhood::penaltyMinCourseDays, and Udine::UseNeighbourhoodLogging.
Referenced by Udine::ContractStrategyI::main(), and Udine::AnytimeStrategyI::main().
{
  try {
    std::stringstream log;
    log << "<neighbourhood ";
    log << "data='" << config.path << "' ";
    log << "discovered='" << config.elapsed() << "' ";
    log << "cost='" << def.cost << "' ";
    log << "penaltyCompactness='" << def.penaltyCompactness << "' ";
    log << "penaltyMinCourseDays='" << def.penaltyMinCourseDays << "' ";
    log << "LB='" << def.lowerBound << "' ";
    log << "'><definition>" << std::endl;
    std::vector<CoursePeriodPair>::iterator itFixPeriod;
    for (itFixPeriod = def.fixPeriod.begin();
         itFixPeriod != def.fixPeriod.end(); itFixPeriod++) {
      log << "<session course='" << itFixPeriod->course << "' ";
      log << " period='" << itFixPeriod->period << "'/>";
    }
    std::vector<CourseDayNumberTriple>::iterator itFixDay;
    for (itFixDay = def.fixDay.begin();
         itFixDay != def.fixDay.end(); itFixDay++) {
      log << "<session course='" << itFixDay->course << "' ";
      log << " day='" << itFixDay->day << "' ";
      log << " events='" << itFixDay->events << "'/>";
    }
    log << "</definition></neighbourhood>";
    if (model.config.getParam(UseNeighbourhoodLogging)) {
      env.out() << "</cplex>\n" << log.str() << "<cplex>" << std::endl;
    }
    std::stringstream filename;
    filename << config.path << ".nei" << (int)def.cost << ".xml";
    std::ofstream neiFile(filename.str().c_str(), ios::app);
    neiFile << log.str() << std::endl;
    neiFile.close();
  }
  catch (...) { std::cerr << "There was an error saving the neighbourhood." << std::endl; return; }
}
virtual void Udine::StrategyI::main () [pure virtual]
Implemented in Udine::AnytimeStrategyI, Udine::ContractStrategyI, Udine::SolutionSavingStrategyI, and Udine::SolutionPolishingStrategyI.
void StrategyI::runDiver (Neighbourhood definition) [virtual]
Definition at line 221 of file strategy.cpp.
References Udine::Config::apply(), config, Udine::Model::config, Udine::Model::conflictGraph, Udine::Neighbourhood::cost, Udine::Model::definition, env, finishOff(), Udine::FixDay, Udine::Config::getParam(), Udine::Model::instance, model, Udine::Config::path, Udine::Neighbourhood::type, and Udine::UseLpFilesExport.
Referenced by Udine::SolutionPolishingStrategyI::finishOff(), Udine::ContractStrategyI::finishOff(), and Udine::AnytimeStrategyI::main().
{
  try {
    IloModel subMIPModel(env);
    Model subMIP(subMIPModel, model.config, model.instance, model.conflictGraph, next);
    IloCplex cplex(subMIPModel);
    if (model.config.getParam(UseLpFilesExport)) {
      std::stringstream filename;
      filename << config.path << "." << next.type << next.cost << ".lp";
      cplex.exportModel(filename.str().c_str());
    }
    env.out() << std::endl << "Diving into the " << next.type << " neighbouhood from ";
    env.out() << model.definition.type << " ..." << std::endl;
    StrategyI *strategy = NULL;
    if (next.type == FixDay)
      strategy = new (env) SolutionPolishingStrategyI(env, subMIP, config);
    else // NOTE: assumes model.config.getParam(UseSolutionLogging)
      strategy = new (env) SolutionSavingStrategyI(env, subMIP, config);
    cplex.use(IloCplex::Callback(strategy));
    config.apply(cplex, next.type);
    cplex.solve();
    strategy->finishOff();
  }
  catch (IloException& e) { std::cerr << "Solver (Strategy): Concert exception caught: " << e << std::endl; }
  catch (...) { std::cerr << "Solver (Strategy): Unknown exception caught." << std::endl; }
}
int StrategyI::sumExtraRoomsUsed () [virtual]
Definition at line 79 of file strategy.cpp.
References Udine::Variables::courseRooms, Udine::Model::definition, Udine::Instance::getCourseCount(), Udine::Instance::getRoomCount(), Udine::Model::instance, model, roundProperly(), Udine::Neighbourhood::type, and Udine::Model::vars.
Referenced by Udine::SolutionSavingStrategyI::main().
{
  int i = 0;
  for (int c = 0; c < model.instance.getCourseCount(); c++)
    for (int r = 0; r < model.instance.getRoomCount(model.definition.type); r++)
      // TODO: Why this could fail
      try { i += roundProperly(getValue(model.vars.courseRooms[c][r])); }
      catch (IloAlgorithm::NotExtractedException e)  { std::cerr << "Error retrieving " << model.vars.courseRooms[c][r].getName() << std::endl; }
      catch (...) { std::cerr << "Error retrieving " << model.vars.courseRooms[c][r].getName() << std::endl; throw; }
  i -= model.instance.getCourseCount();
  return i;
}
int StrategyI::sumMissingCourseDays () [virtual]
Definition at line 32 of file strategy.cpp.
References Udine::Variables::courseMinDayViolations, Udine::Model::definition, Udine::FixDay, Udine::FixPeriod, Udine::Instance::getCourseCount(), Udine::Model::instance, model, Udine::Neighbourhood::penaltyMinCourseDays, roundProperly(), Udine::Neighbourhood::type, and Udine::Model::vars.
Referenced by getFixDayNeighbourhood(), getFixPeriodNeighbourhood(), and Udine::SolutionSavingStrategyI::main().
{
  if (model.definition.type == FixDay || model.definition.type == FixPeriod)
    return model.definition.penaltyMinCourseDays;
  int i = 0;
  for (int c = 0; c < model.instance.getCourseCount(); c++)
    try { i += roundProperly(getValue(model.vars.courseMinDayViolations[c])); }
    catch (IloAlgorithm::NotExtractedException e)  { std::cerr << "Error retrieving " << model.vars.courseMinDayViolations[c].getName() << "." << std::endl; }
    catch (...)  { std::cerr << "Unknown error retrieving " << model.vars.courseMinDayViolations[c].getName() << "." << std::endl; throw; }
  return i;
}
int StrategyI::sumMissingSeats () [virtual]
Definition at line 64 of file strategy.cpp.
References Udine::Model::definition, Udine::Instance::getCourse(), Udine::Instance::getCourseCount(), Udine::Instance::getPeriodCount(), Udine::Instance::getRoomCount(), Udine::Instance::getRoomPerEventCapacity(), Udine::Model::instance, model, roundProperly(), Udine::Course::students, Udine::Neighbourhood::type, Udine::Model::vars, and Udine::Variables::x.
Referenced by Udine::SolutionSavingStrategyI::main().
{
  int i = 0;
  for (int r = 0; r < model.instance.getRoomCount(model.definition.type); r++)
    for (int c = 0; c < model.instance.getCourseCount(); c++)
      if (model.instance.getCourse(c).students > model.instance.getRoomPerEventCapacity(model.definition.type, r))
        for (int p = 0; p < model.instance.getPeriodCount(); p++)
          try {
            if (roundProperly(getValue(model.vars.x[p][r][c])) == 1)
              i += model.instance.getCourse(c).students - model.instance.getRoomPerEventCapacity(model.definition.type, r);
          }
          catch (IloAlgorithm::NotExtractedException e)  { std::cerr << "Error retrieving " << model.vars.x[p][r][c].getName() << std::endl; }
          catch (...) { std::cerr << "Error retrieving " << model.vars.x[p][r][c].getName() << std::endl; throw; }
  return i;
}
int StrategyI::sumSingletonChecks () [virtual]
Definition at line 44 of file strategy.cpp.
References config, Udine::Model::definition, Udine::FixDay, Udine::FixPeriod, Udine::Instance::getCheckCount(), Udine::Instance::getDayCount(), Udine::Config::getParam(), Udine::Instance::getProperCurriculumCount(), Udine::Model::instance, model, Udine::Neighbourhood::penaltyCompactness, roundProperly(), Udine::Variables::singletonChecks, Udine::Surface, Udine::Neighbourhood::type, Udine::UseHeuristicCompactnessAtSurface, Udine::UseHeuristicCompactnessInDayDives, and Udine::Model::vars.
Referenced by getFixDayNeighbourhood(), getFixPeriodNeighbourhood(), and Udine::SolutionSavingStrategyI::main().
{
  if (model.definition.type == FixPeriod)
    return model.definition.penaltyCompactness;
  int i = 0;
  // TODO: if (config.getParam(UseSpreadOnlyNeighbourhoods)) return i;
  int limit = model.instance.getCheckCount();
  if ((model.definition.type == Surface && config.getParam(UseHeuristicCompactnessAtSurface))
      || (model.definition.type == FixDay && config.getParam(UseHeuristicCompactnessInDayDives)))
    limit = 1;
  for (int u = 0; u < model.instance.getProperCurriculumCount(); u++)
    for (int d = 0; d < model.instance.getDayCount(); d++)
      for (int s = 0; s < limit; s++)
        try { i += roundProperly(getValue(model.vars.singletonChecks[u][d][s])); }
        catch (IloAlgorithm::NotExtractedException e)  { std::cerr << "Error retrieving " << model.vars.singletonChecks[u][d][s].getName() << std::endl; }
        catch (...) { std::cerr << "Error retrieving " << model.vars.singletonChecks[u][d][s].getName() << std::endl; throw; }
  return i;
}
Field Documentation
Config& Udine::StrategyI::config [protected]
Definition at line 45 of file strategy.h.
Referenced by Udine::SolutionPolishingStrategyI::finishOff(), Udine::ContractStrategyI::finishOff(), logNeighbrouhood(), Udine::SolutionPolishingStrategyI::main(), Udine::SolutionSavingStrategyI::main(), Udine::AnytimeStrategyI::main(), runDiver(), and sumSingletonChecks().
IloEnv Udine::StrategyI::env [protected]
Definition at line 44 of file strategy.h.
Referenced by getFixDayNeighbourhood(), getFixPeriodNeighbourhood(), logNeighbrouhood(), Udine::SolutionSavingStrategyI::main(), and runDiver().
Model& Udine::StrategyI::model [protected]
Definition at line 46 of file strategy.h.
Referenced by getFixDayNeighbourhood(), getFixPeriodNeighbourhood(), logNeighbrouhood(), Udine::SolutionPolishingStrategyI::main(), Udine::SolutionSavingStrategyI::main(), runDiver(), sumExtraRoomsUsed(), sumMissingCourseDays(), sumMissingSeats(), and sumSingletonChecks().
The documentation for this class was generated from the following files:
src/strategy.h
src/strategy.cpp