MemosTimetabling: Udine::Solver Class Reference
Udine::Solver Class Reference
#include <solver.h>
Public Member Functions
Solver (IloEnv &env, Config &config)
virtual ~Solver ()
Detailed Description
Definition at line 34 of file solver.h.
Constructor & Destructor Documentation
Solver::Solver (IloEnv & env, Config & config)
Definition at line 32 of file solver.cpp.
References Udine::AnytimeAlgorithm, Udine::Config::apply(), Udine::BoundSaver(), Udine::Config::configId, Udine::ContractAlgorithm, Udine::Neighbourhood::cost, Udine::CutManager(), Udine::Config::elapsed(), Udine::StrategyI::finishOff(), Udine::Graph::generateCliques(), Udine::Graph::generateConflictGraph(), Udine::Config::getParam(), Udine::Instance::load(), Udine::Config::path, Udine::Config::strategy, Udine::Surface, Udine::Neighbourhood::type, Udine::UseDynamicCutsAtSurface, Udine::UseLowerBoundLogging, and Udine::UseLpFilesExport.
{
  try {
    env.out() << "<?xml version='1.0' encoding='UTF-8'?>" << std::endl;
    env.out() << "<log";
    env.out() << " data='" << config.path << "' ";
    env.out() << " config='" << config.configId << "' ";
    env.out() << ">" << std::endl;
    env.out() << "<cplex>";
    IloModel model(env);
    IloCplex cplex(model);
    config.apply(cplex, Surface);
    Instance instance;
    instance.load(config.path);
    Graph conflictGraph;
    conflictGraph.generateConflictGraph(instance);
    conflictGraph.generateCliques();
    Neighbourhood definition;
    definition.type = Surface;
    definition.cost = 0;
    Model surface(model, config, instance, conflictGraph, definition);
    if (config.getParam(UseLpFilesExport)) {
      env.out() << std::endl << "Exporting the surface model ..." << std::endl;
      std::stringstream filename;
      filename << config.path << ".surface.lp";
      cplex.exportModel(filename.str().c_str());
    }
    StrategyI *strategy = NULL;
    switch (config.strategy) {
      case ContractAlgorithm:
        strategy = new (env) ContractStrategyI(env, surface, config);
        break;
      case AnytimeAlgorithm:
      default:
        strategy = new (env) AnytimeStrategyI(env, surface, config);
        break;
    }
    cplex.use(IloCplex::Callback(strategy));
    if (config.getParam(UseLowerBoundLogging))
      cplex.use(BoundSaver(env, config, "globalLB"));
    if (config.getParam(UseDynamicCutsAtSurface))
      cplex.use(CutManager(env, surface, config));
    env.out() << std::endl << "Solver: Running ..." << std::endl;
#if CPX_VERSION >= 1100
    cplex.populate();
#else
    cplex.solve();
#endif
    if (cplex.getStatus() != IloAlgorithm::Feasible &&
        cplex.getStatus() != IloAlgorithm::Optimal) {
      env.out() << "Solver: Not a single neighbourhood has been found. Please check the time limit and feasibility of the instance." << std::endl;
    }
    env.out() << "</cplex>";
    env.out() << "<timestamp end='" << config.elapsed() << "'/>";
    strategy->finishOff();
    env.out() << "</log>" << std::endl;
  }
  catch (IloException& e) { env.error() << "Solver: Concert exception caught: " << e << std::endl; }
  catch (...) { env.error() << "Solver: Unknown exception caught" << std::endl; }
}
virtual Udine::Solver::~Solver () [inline, virtual]
Definition at line 37 of file solver.h.
{ }
The documentation for this class was generated from the following files:
src/solver.h
src/solver.cpp