MemosTimetabling: Udine::SolutionSavingStrategyI Class Reference
Udine::SolutionSavingStrategyI Class Reference
#include <strategy.h>
Public Member Functions
SolutionSavingStrategyI (IloEnv &environment, Model &s, Config &configuration)
virtual void main ()
virtual void finishOff ()
Detailed Description
Definition at line 101 of file strategy.h.
Constructor & Destructor Documentation
Udine::SolutionSavingStrategyI::SolutionSavingStrategyI (IloEnv & environment, Model & s, Config & configuration) [inline]
Definition at line 104 of file strategy.h.
  : StrategyI(environment, s, configuration) {
  }
Member Function Documentation
void SolutionSavingStrategyI::finishOff () [virtual]
Implements Udine::StrategyI.
Definition at line 395 of file strategy.cpp.
{
}
void SolutionSavingStrategyI::main () [virtual]
Implements Udine::StrategyI.
Definition at line 321 of file strategy.cpp.
References Udine::Config::addSolutionCost(), Udine::StrategyI::config, Udine::Model::definition, Udine::Config::elapsed(), Udine::StrategyI::env, Udine::Instance::getCourse(), Udine::Instance::getCourseCount(), Udine::Instance::getPeriodCount(), Udine::Instance::getPeriodsPerDayCount(), Udine::Instance::getRoomCount(), Udine::Instance::getRoomName(), Udine::Config::getWeights(), Udine::Model::instance, Udine::StrategyI::model, Udine::Course::name, Udine::Config::path, roundProperly(), Udine::StrategyI::sumExtraRoomsUsed(), Udine::StrategyI::sumMissingCourseDays(), Udine::StrategyI::sumMissingSeats(), Udine::StrategyI::sumSingletonChecks(), Udine::Neighbourhood::type, Udine::Model::vars, Udine::ObjectiveWeights::wCompactness, Udine::ObjectiveWeights::wMinDays, Udine::ObjectiveWeights::wRoomCapacity, Udine::ObjectiveWeights::wRoomStability, and Udine::Variables::x.
{
  try {
    std::stringstream log;
    std::stringstream sol;
    int pRoomCapacity = sumMissingSeats();
    int pMinDays = sumMissingCourseDays();
    int pCompactness = sumSingletonChecks();
    int pRoomStability = sumExtraRoomsUsed();
    int pTotal =
      config.getWeights(model.definition.type).wMinDays * pMinDays +
      config.getWeights(model.definition.type).wCompactness * pCompactness +
      config.getWeights(model.definition.type).wRoomCapacity * pRoomCapacity +
      config.getWeights(model.definition.type).wRoomStability * pRoomStability;
    log << "<solution submodelCost='" << getObjValue() << "' ";
    log << "cost='" << pTotal << "' ";
    log << "data='" << config.path << "' ";
    log << "type='" << model.definition.type << "' ";
    log << "discovered='" << config.elapsed() << "' ";
    log << "neighbourhoodLB='" << getBestObjValue() << "' ";
    log << "penaltyRoomCapacity='" << pRoomCapacity << "' ";
    log << "penaltyMinCourseDays='" << pMinDays << "' ";
    log << "penaltyCompactness='" << pCompactness << "' ";
    log << "penaltyRoomStability='" << pRoomStability << "' ";
    log << ">\n";
    int c, p, r;  // course, period, room
    for(c = 0; c < model.instance.getCourseCount(); c++)
      for(p = 0; p < model.instance.getPeriodCount(); p++) {
        int day = (int)std::floor(float(p / model.instance.getPeriodsPerDayCount()));
        int periodWithin = p % model.instance.getPeriodsPerDayCount();
        for(r = 0; r < model.instance.getRoomCount(model.definition.type); r++)
          try {
            if (roundProperly(getValue(model.vars.x[p][r][c])) == 1) {
              log << "<session course='" << model.instance.getCourse(c).name;
              log << "' room='" << model.instance.getRoomName(r);
              log << "' period='" << p;
              log << "' day='" << day;
              log << "' periodWithin='" << periodWithin;
              log << "'/> ";
              sol << model.instance.getCourse(c).name << " ";
              sol << model.instance.getRoomName(r) << " ";
              sol << day << " " << periodWithin << "\n";
            }
          } catch (IloAlgorithm::NotExtractedException e)  { std::cerr << "Error retrieving " << model.vars.x[p][r][c].getName() << "." << std::endl; }
            catch (...)  { std::cerr << "Unknown error retrieving " << model.vars.x[p][r][c].getName() << "." << std::endl; throw; }
      }
    log << "</solution>\n";
    env.out() << "</cplex>\n" << log.str();
    env.out() << "\n<cplex>" << std::endl;
    std::stringstream xmlname;
    xmlname << config.path << ".sol" << pTotal << ".xml";
    std::ofstream solFile(xmlname.str().c_str(), ios::out);
    solFile << log.str() << std::endl;
    solFile.close();
    std::stringstream solname;
    solname << config.path << ".sol" << pTotal << ".out";
    solFile.open(solname.str().c_str(), ios::out);
    solFile << sol.str() << std::endl;
    solFile.close();
    config.addSolutionCost(model.definition.type, pTotal);
  }
  catch (IloException& e) { env.error() << "Concert error: " << e << std::endl; }
  catch (...) { env.error() << "Unknown error: " << std::endl; throw; }
}
The documentation for this class was generated from the following files:
src/strategy.h
src/strategy.cpp