MemosTimetabling: Udine::AnytimeStrategyI Class Reference
Udine::AnytimeStrategyI Class Reference
#include <strategy.h>
Public Member Functions
AnytimeStrategyI (IloEnv &environment, Model &s, Config &configuration)
virtual void main ()
virtual void finishOff ()
Detailed Description
Definition at line 70 of file strategy.h.
Constructor & Destructor Documentation
Udine::AnytimeStrategyI::AnytimeStrategyI (IloEnv & environment, Model & s, Config & configuration) [inline]
Definition at line 73 of file strategy.h.
  : StrategyI(environment, s, configuration) {
  }
Member Function Documentation
void AnytimeStrategyI::finishOff () [virtual]
Implements Udine::StrategyI.
Definition at line 276 of file strategy.cpp.
{
}
void AnytimeStrategyI::main () [virtual]
Implements Udine::StrategyI.
Definition at line 261 of file strategy.cpp.
References Udine::Config::anytimeDivingOnset, Udine::StrategyI::config, Udine::Config::elapsed(), Udine::FixDay, Udine::FixPeriod, Udine::StrategyI::getFixDayNeighbourhood(), Udine::StrategyI::getFixPeriodNeighbourhood(), Udine::StrategyI::logNeighbrouhood(), and Udine::StrategyI::runDiver().
{
  if (   config.anytimeDivingOnset[FixPeriod] >= 0
      && config.elapsed() > config.anytimeDivingOnset[FixPeriod]) {
      Neighbourhood def = getFixPeriodNeighbourhood();
      logNeighbrouhood(def);
      runDiver(def);
    }
  if (   config.anytimeDivingOnset[FixDay] >= 0
      && config.elapsed() > config.anytimeDivingOnset[FixDay]) {
      Neighbourhood def = getFixDayNeighbourhood();
      logNeighbrouhood(def);
      runDiver(def);
    }
}
The documentation for this class was generated from the following files:
src/strategy.h
src/strategy.cpp