MemosTimetabling: Udine::Instance Class Reference
Udine::Instance Class Reference
#include <loader.h>
Public Member Functions
Instance ()
void load (const char *filename)
int getPeriodCount ()
int getDayCount ()
int getPeriodsPerDayCount ()
int getCheckCount ()
int getCourseCount ()
int getProperCurriculumCount ()
int getCurriculumCount ()
int getRestrictionCount ()
const Course & getCourse (int i)
const Curriculum & getCurriculum (int u)
const Restriction & getRestriction (int i)
int getRoomCount (ModelType t)
int getRoomTotalMultiplicity (ModelType t)
const std::string getRoomName (int r)
int getRoomMultiplicity (ModelType t, int r)
int getRoomPerEventCapacity (ModelType t, int r)
PatternDB & getPatterns ()
Protected Member Functions
void genPatterns (int periodsPerDay, int rhs=-1, std::vector< int > soFar=std::vector< int >())
void genMRoomsAggregates ()
Protected Attributes
int periods
int periodsPerDay
int days
int checks
Courses courses
Rooms rooms
MRoomsVersions mRooms
int origCurricula
Curricula curricula
Restrictions restrict
PatternDB patterns
Detailed Description
Definition at line 78 of file loader.h.
Constructor & Destructor Documentation
Udine::Instance::Instance () [inline]
Definition at line 94 of file loader.h.
: mRooms(MRoomsVersions(ModelTypeLen)) {}
Member Function Documentation
void Instance::genMRoomsAggregates () [protected]
Definition at line 229 of file loader.cpp.
References Udine::FixDay, Udine::FixPeriod, Udine::ModelTypeLen, Udine::Monolithic, mRooms, Udine::MRoom::multiplicity, Udine::MRoom::perEventCapacity, Udine::MRoom::rooms, rooms, and Udine::Surface.
Referenced by load().
{
  for (int type = 0; type < ModelTypeLen; type++) {
    switch(type) {
      case Monolithic:
      case FixPeriod:
      {
        for (int i = 0; i < rooms.size(); i++) {
          MRoom room;
          room.multiplicity = 1;
          room.perEventCapacity = rooms.at(i).capacity;
          room.rooms.push_back(rooms.at(i));
          mRooms.at(type).push_back(room);
        }
      }
      break;
      case FixDay:
      {
        MRoom mRoom;
        for (int i = 0; i < rooms.size() - 1; i++) {
          mRoom.multiplicity += 1;
          mRoom.perEventCapacity = std::max(mRoom.perEventCapacity, rooms.at(i).capacity);
          mRoom.rooms.push_back(rooms.at(i));
          if (rooms.at(i).capacity != rooms.at(i + 1).capacity) {
            mRooms.at(type).push_back(mRoom);
            mRoom.rooms.clear();
            mRoom.multiplicity = 0;
            mRoom.perEventCapacity = rooms.at(i + 1).capacity;
          }
        }
        mRoom.multiplicity += 1;
        mRoom.perEventCapacity = rooms.at(rooms.size() - 1).capacity;
        mRoom.rooms.push_back(rooms.at(rooms.size() - 1));
        mRooms.at(type).push_back(mRoom);
      }
      break;
      case Surface:
      {
        MRoom large, small;
        int i;
        std::vector<int> distinct;
        distinct.push_back(rooms.at(0).capacity);
        for (i = 1; i < rooms.size(); i++) {
          if (rooms.at(i - 1).capacity != rooms.at(i).capacity)
            distinct.push_back(rooms.at(i).capacity);
        }
        /*
        float cost = 0;
        for (i = 0; i < distinct.size() - 1; i++) {
          int now = abs(distinct.at(i) - distinct.at(i + 1)) /
                    (0.2 * abs((int)(i - distinct.size())));
          std::cout << abs(distinct.at(i) - distinct.at(i + 1)) << " "
            << abs((int)(i - distinct.size() - 1)) << std::endl;
          if (now > cost)
            splitAt = (distinct.at(i) + distinct.at(i + 1)) / 2;
        }
        */
        float splitAt = distinct.at(floor((float)(distinct.size() / 2))) + 1;
        for (i = 0; i < rooms.size(); i++) {
          if (rooms.at(i).capacity < splitAt) {
            small.multiplicity += 1;
            small.perEventCapacity = std::max(small.perEventCapacity, rooms.at(i).capacity);
            small.rooms.push_back(rooms.at(i));
          } else {
            large.multiplicity += 1;
            large.perEventCapacity = std::max(large.perEventCapacity, rooms.at(i).capacity);
            large.rooms.push_back(rooms.at(i));
          }
        }
        std::cout << "The surface mRooms have capacity " << small.perEventCapacity;
        std::cout << " and " << large.perEventCapacity << std::endl;
        mRooms.at(type).push_back(small);
        mRooms.at(type).push_back(large);
        /*
        for (i = 0; i < rooms.size(); i++) {
          small.multiplicity += 1;
          small.perEventCapacity = std::max(small.perEventCapacity, rooms.at(i).capacity);
          small.rooms.push_back(rooms.at(i));
        }
        mRooms.at(type).push_back(small);
        */
      }
      break;
    }
  }
}
void Instance::genPatterns (int periodsPerDay, int rhs = -1, std::vector< int > soFar = std::vector<int>()) [protected]
Definition at line 183 of file loader.cpp.
References Udine::Pattern::coefs, patterns, Udine::Pattern::penalty, and Udine::Pattern::rhs.
Referenced by load().
{
  const int minus = -1;
  const int plus = 1;
  // Recursion
  if (toAdd > 0) {
    pat.push_back(minus);
    genPatterns(toAdd - 1, rhs, pat);
    pat.pop_back();
    pat.push_back(plus);
    genPatterns(toAdd - 1, rhs + plus, pat);
    return;
  }
  // Evaluate the pattern, if complete
  int penalty = 0;
  int last = pat.size() - 1;
  if (pat.size() < 3) return;
  if (pat[0] == plus && pat[1] == minus) penalty += 1;
  if (pat[last] == plus && pat[last - 1] == minus) penalty += 1;
  for (int i = 0; i < pat.size() - 2; i++)
    if (pat[i] == minus && pat[i + 1] == plus && pat[i + 2] == minus)
      penalty += 1;
  // Save it if it has attracted any penalty
  if (penalty > 0) {
    Pattern p;
    p.coefs = pat;
    p.penalty = penalty;
    p.rhs = rhs;
    patterns.push_back(p);
  }
} // END of Instance::genPatters()
int Udine::Instance::getCheckCount () [inline]
Definition at line 101 of file loader.h.
References checks.
Referenced by Udine::CutManagerI::genCutsFromPatterns(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::StrategyI::sumSingletonChecks(), and Udine::Variables::Variables().
{ return checks; }
const Course& Udine::Instance::getCourse (int i) [inline]
Definition at line 107 of file loader.h.
References courses.
Referenced by Udine::Model::generateCoursePeriods(), Udine::Model::generateHardConstraints(), Udine::Model::generateMinCourseDays(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::Model::generateRoomStability(), Udine::SolutionSavingStrategyI::main(), and Udine::StrategyI::sumMissingSeats().
{
    assert(i >= 0 && i < courses.size());
    return courses.at(i);
  }
int Udine::Instance::getCourseCount () [inline]
Definition at line 102 of file loader.h.
References courses.
Referenced by Udine::Graph::generateConflictGraph(), Udine::Model::generateCoursePeriods(), Udine::Model::generateHardConstraints(), Udine::Model::generateMinCourseDays(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::Model::generateRoomStability(), Udine::StrategyI::getFixDayNeighbourhood(), Udine::StrategyI::getFixPeriodNeighbourhood(), Udine::SolutionSavingStrategyI::main(), Udine::StrategyI::sumExtraRoomsUsed(), Udine::StrategyI::sumMissingCourseDays(), Udine::StrategyI::sumMissingSeats(), and Udine::Variables::Variables().
{ return courses.size(); }
const Curriculum& Udine::Instance::getCurriculum (int u) [inline]
Definition at line 112 of file loader.h.
References curricula.
Referenced by Udine::CutManagerI::genCutsFromPatterns(), Udine::CutManagerI::genCutsFromPatternsWithHeuristicAtSurface(), Udine::Model::generateCompactness(), Udine::Graph::generateConflictGraph(), Udine::Model::generateCoursePeriods(), and Udine::Model::generateHardConstraints().
{
    assert(u >= 0 && u < curricula.size());
    return curricula.at(u);
  }
int Udine::Instance::getCurriculumCount () [inline]
Definition at line 104 of file loader.h.
References curricula.
Referenced by Udine::Graph::generateConflictGraph(), Udine::Model::generateCoursePeriods(), and Udine::Model::generateHardConstraints().
{ return curricula.size(); }
int Udine::Instance::getDayCount () [inline]
Definition at line 99 of file loader.h.
References days.
Referenced by Udine::CutManagerI::genCutsFromPatterns(), Udine::CutManagerI::genCutsFromPatternsWithHeuristicAtSurface(), Udine::Model::generateCompactness(), Udine::Model::generateMinCourseDays(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::StrategyI::getFixDayNeighbourhood(), Udine::StrategyI::sumSingletonChecks(), and Udine::Variables::Variables().
{ return days; }
PatternDB& Udine::Instance::getPatterns () [inline]
Definition at line 152 of file loader.h.
References patterns.
Referenced by Udine::CutManagerI::genCutsFromPatterns(), and Udine::CutManagerI::genCutsFromPatternsWithHeuristicAtSurface().
{
    return patterns;
  }
int Udine::Instance::getPeriodCount () [inline]
Definition at line 98 of file loader.h.
References periods.
Referenced by Udine::CutManagerI::genCutsFromCliquePool(), Udine::CutManagerI::genCutsFromTriangles(), Udine::Model::generateCoursePeriods(), Udine::Model::generateHardConstraints(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::Model::generateRoomStability(), Udine::StrategyI::getFixPeriodNeighbourhood(), Udine::SolutionSavingStrategyI::main(), Udine::StrategyI::sumMissingSeats(), and Udine::Variables::Variables().
{ return periods; }
int Udine::Instance::getPeriodsPerDayCount () [inline]
Definition at line 100 of file loader.h.
Referenced by Udine::CutManagerI::genCutsFromPatterns(), Udine::CutManagerI::genCutsFromPatternsWithHeuristicAtSurface(), Udine::Model::generateCompactness(), Udine::Model::generateMinCourseDays(), Udine::Model::generateNeighbourhood(), Udine::StrategyI::getFixDayNeighbourhood(), and Udine::SolutionSavingStrategyI::main().
{ return periodsPerDay; }
int Udine::Instance::getProperCurriculumCount () [inline]
Definition at line 103 of file loader.h.
References origCurricula.
Referenced by Udine::CutManagerI::genCutsFromPatterns(), Udine::CutManagerI::genCutsFromPatternsWithHeuristicAtSurface(), Udine::Model::generateCompactness(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::StrategyI::sumSingletonChecks(), and Udine::Variables::Variables().
{ return origCurricula; }
const Restriction& Udine::Instance::getRestriction (int i) [inline]
Definition at line 117 of file loader.h.
References restrict.
Referenced by Udine::Model::generateHardConstraints().
{
    assert(i >= 0 && i < restrict.size());
    return restrict.at(i);
  }
int Udine::Instance::getRestrictionCount () [inline]
Definition at line 105 of file loader.h.
References restrict.
Referenced by Udine::Model::generateHardConstraints().
{ return restrict.size(); }
int Udine::Instance::getRoomCount (ModelType t) [inline]
Definition at line 122 of file loader.h.
References Udine::ModelTypeLen, and mRooms.
Referenced by Udine::Model::generateCompactness(), Udine::Model::generateCoursePeriods(), Udine::Model::generateHardConstraints(), Udine::Model::generateMinCourseDays(), Udine::Model::generateNeighbourhood(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::Model::generateRoomStability(), Udine::StrategyI::getFixDayNeighbourhood(), Udine::StrategyI::getFixPeriodNeighbourhood(), Udine::SolutionSavingStrategyI::main(), Udine::StrategyI::sumExtraRoomsUsed(), Udine::StrategyI::sumMissingSeats(), and Udine::Variables::Variables().
{
    assert(t >= 0 && t < ModelTypeLen);
    return mRooms.at(t).size();
  }
int Udine::Instance::getRoomMultiplicity (ModelType t, int r) [inline]
Definition at line 140 of file loader.h.
References Udine::ModelTypeLen, and mRooms.
Referenced by Udine::Model::generateHardConstraints().
{
    assert(t >= 0 && t < ModelTypeLen);
    assert(r >= 0 && r < mRooms.at(t).size());
    return mRooms.at(t).at(r).multiplicity;
  }
const std::string Udine::Instance::getRoomName (int r) [inline]
Definition at line 135 of file loader.h.
References rooms.
Referenced by Udine::SolutionSavingStrategyI::main().
{
    assert(r >= 0 && r < rooms.size());
    return rooms.at(r).name;
  }
int Udine::Instance::getRoomPerEventCapacity (ModelType t, int r) [inline]
Definition at line 146 of file loader.h.
References Udine::ModelTypeLen, and mRooms.
Referenced by Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), and Udine::StrategyI::sumMissingSeats().
{
    assert(t >= 0 && t < ModelTypeLen);
    assert(r >= 0 && r < mRooms.at(t).size());
    return mRooms.at(t).at(r).perEventCapacity;
  }
int Udine::Instance::getRoomTotalMultiplicity (ModelType t) [inline]
Definition at line 127 of file loader.h.
References Udine::ModelTypeLen, and mRooms.
Referenced by Udine::Model::generateCoursePeriods(), and Udine::Model::generateHardConstraints().
{
    assert(t >= 0 && t < ModelTypeLen);
    int multiplicity = 0;
    for(int r = 0; r < mRooms.at(t).size(); r++)
      multiplicity += mRooms.at(t).at(r).multiplicity;
    return multiplicity;
  }
void Instance::load (const char * filename)
Definition at line 56 of file loader.cpp.
References Udine::Room::capacity, checks, Udine::Restriction::courseId, Udine::Curriculum::courseIds, courses, curricula, days, genMRoomsAggregates(), genPatterns(), Udine::Course::lectures, Udine::Curriculum::name, Udine::Room::name, origCurricula, Udine::Restriction::period, periods, periodsPerDay, restrict, and rooms.
Referenced by Udine::Solver::Solver().
{
  try {
    std::ifstream file;
    file.open(filename, std::ifstream::in);
    std::string forget; int i;
    std::map< std::string, int, std::less<std::string> > cnames;
    std::string iname;
    int courseCnt, eventCnt, roomCnt, dayCnt, curriculumCnt, constraintCnt;
    // load the header
    file >> forget >> iname;
    file >> forget >> courseCnt; eventCnt = 0;
    file >> forget >> roomCnt;
    file >> forget >> dayCnt;
    file >> forget >> periodsPerDay;
    file >> forget >> curriculumCnt;
    file >> forget >> constraintCnt;
    periods = dayCnt * periodsPerDay;
    days = dayCnt;
    checks = periodsPerDay;
    std::cout << "Loader: Instance " << iname << " (" << filename << ")"<< std::endl;
    // courses
    file >> forget;
    for (i = 0; i < courseCnt; i++) {
      Course c;
      assert(file.good());
      file >> c;
      cnames[c.name] = i;
      eventCnt += c.lectures;
      courses.push_back(c);
    }
    // rooms and their capacities
    file >> forget;
    for (i = 0; i < roomCnt; i++) {
      Room room;
      assert(file.good());
      file >> room.name >> room.capacity;
      rooms.push_back(room);
    }
    RoomCapacityLess capacityLess;
    std::sort(rooms.begin(), rooms.end(), capacityLess);
    genMRoomsAggregates();
    // groups of conflicting courses
    file >> forget;
    for (i = 0; i < curriculumCnt; i++) {
      Curriculum u; int ccount;
      file >> u.name >> ccount;
      for (int j = 0; j < ccount; j++) {
        std::string s;
        assert(file.good());
        file >> s;
        assert(cnames.find(s) != cnames.end());
        u.courseIds.push_back(cnames.find(s)->second);
      }
      curricula.push_back(u);
    }
    origCurricula = curricula.size();
    // restrictions on times when teachers are available
    file >> forget;
    for (i = 0; i < constraintCnt; i++) {
      std::string cname; int day; int period;
      assert(file.good());
      file >> cname >> day >> period;
      Restriction r;
      assert(cnames.find(cname) != cnames.end());
      r.courseId = cnames.find(cname)->second;
      r.period = day * periodsPerDay + period;
      restrict.push_back(r);
    }
    // make an overview of who teaches what
    typedef std::map< std::string, std::vector<int>, std::less<std::string> > s2veci;
    s2veci tnames;
    std::vector<Course>::iterator it = courses.begin();
    for (i = 0; it != courses.end(); it++, i++) {
      if (tnames.find(it->teacher) == tnames.end()) {
        std::vector<int> teaches;
        teaches.push_back(i);
        tnames[it->teacher] = teaches;
      } else {
        tnames.find(it->teacher)->second.push_back(i);
      }
    }
    // look for teachers teaching more than a single course
    s2veci::iterator mapit = tnames.begin();
    for (; mapit != tnames.end(); mapit++) {
      if (mapit->second.size() > 1) {
        // create artificial curricula out of this
        Curriculum c;
        c.courseIds = mapit->second;
        c.name = mapit->first;
        curricula.push_back(c);
      }
    }
    if (file.bad()) {
      std::cout << "Loader: Instance incomplete!" << std::endl;
      abort();
    } else {
      std::cout << "Loader: " << courseCnt << " courses, ";
      std::cout << eventCnt << " events, and ";
      std::cout << curriculumCnt << " curricula" << std::endl;
    }
    file.close();
    genPatterns(periodsPerDay);
  } catch (std::exception &e) {
    std::cerr << "Loader: There was an error reading the instance!" << std::endl;
    std::cerr << "Exception says: " << e.what() << std::endl;
    abort();
  }
}  // END of Instance::load
Field Documentation
int Udine::Instance::checks [protected]
Definition at line 80 of file loader.h.
Referenced by getCheckCount(), and load().
Courses Udine::Instance::courses [protected]
Definition at line 81 of file loader.h.
Referenced by getCourse(), getCourseCount(), and load().
Curricula Udine::Instance::curricula [protected]
Definition at line 85 of file loader.h.
Referenced by getCurriculum(), getCurriculumCount(), and load().
int Udine::Instance::days [protected]
Definition at line 80 of file loader.h.
Referenced by getDayCount(), and load().
MRoomsVersions Udine::Instance::mRooms [protected]
Definition at line 83 of file loader.h.
Referenced by genMRoomsAggregates(), getRoomCount(), getRoomMultiplicity(), getRoomPerEventCapacity(), and getRoomTotalMultiplicity().
int Udine::Instance::origCurricula [protected]
Definition at line 84 of file loader.h.
Referenced by getProperCurriculumCount(), and load().
PatternDB Udine::Instance::patterns [protected]
Definition at line 87 of file loader.h.
Referenced by genPatterns(), and getPatterns().
int Udine::Instance::periods [protected]
Definition at line 80 of file loader.h.
Referenced by getPeriodCount(), and load().
int Udine::Instance::periodsPerDay [protected]
Definition at line 80 of file loader.h.
Referenced by load().
Restrictions Udine::Instance::restrict [protected]
Definition at line 86 of file loader.h.
Referenced by getRestriction(), getRestrictionCount(), and load().
Rooms Udine::Instance::rooms [protected]
Definition at line 82 of file loader.h.
Referenced by genMRoomsAggregates(), getRoomName(), and load().
The documentation for this class was generated from the following files:
src/loader.h
src/loader.cpp