MemosTimetabling: Udine::ContractStrategyI Class Reference
Udine::ContractStrategyI Class Reference
#include <strategy.h>
Public Member Functions
ContractStrategyI (IloEnv &environment, Model &s, Config &configuration)
virtual void main ()
virtual void finishOff ()
Protected Attributes
Neighbourhoods fixDayNeighbs
Neighbourhoods fixPeriodNeighbs
Detailed Description
Definition at line 84 of file strategy.h.
Constructor & Destructor Documentation
Udine::ContractStrategyI::ContractStrategyI (IloEnv & environment, Model & s, Config & configuration) [inline]
Definition at line 90 of file strategy.h.
  : StrategyI(environment, s, configuration) {
  }
Member Function Documentation
void ContractStrategyI::finishOff () [virtual]
Implements Udine::StrategyI.
Definition at line 293 of file strategy.cpp.
References Udine::StrategyI::config, Udine::Config::contractTimelimit, Udine::Config::elapsed(), Udine::FixDayDiveFromSurface, fixDayNeighbs, Udine::FixPeriodDiveFromSurface, fixPeriodNeighbs, Udine::Config::getCount(), and Udine::StrategyI::runDiver().
{
  int counter = 0;
  while  (config.elapsed() < config.contractTimelimit
       && !fixPeriodNeighbs.empty()
       && counter < config.getCount(FixPeriodDiveFromSurface))
    try {
      runDiver(fixPeriodNeighbs.back());
      fixPeriodNeighbs.pop_back();
      counter += 1;
    } catch (std::exception &e) { std::cerr << "Solver (FixPeriod Dives): " << e.what() << std::endl; }
  counter = 0;
  while   (config.elapsed() < config.contractTimelimit
        && !fixDayNeighbs.empty()
        && counter < config.getCount(FixDayDiveFromSurface)) {
    try {
      runDiver(fixDayNeighbs.back());
      fixDayNeighbs.pop_back();
      counter += 1;
    } catch (std::exception &e) { std::cerr << "Solver (FixDay Dives): " << e.what() << std::endl; }
  }
}
void ContractStrategyI::main () [virtual]
Implements Udine::StrategyI.
Definition at line 287 of file strategy.cpp.
References fixDayNeighbs, fixPeriodNeighbs, Udine::StrategyI::getFixDayNeighbourhood(), Udine::StrategyI::getFixPeriodNeighbourhood(), and Udine::StrategyI::logNeighbrouhood().
{
  fixDayNeighbs.push_back(getFixDayNeighbourhood());
  fixPeriodNeighbs.push_back(getFixPeriodNeighbourhood());
  logNeighbrouhood(fixDayNeighbs.back());
}
Field Documentation
Neighbourhoods Udine::ContractStrategyI::fixDayNeighbs [protected]
Definition at line 86 of file strategy.h.
Referenced by finishOff(), and main().
Neighbourhoods Udine::ContractStrategyI::fixPeriodNeighbs [protected]
Definition at line 87 of file strategy.h.
Referenced by finishOff(), and main().
The documentation for this class was generated from the following files:
src/strategy.h
src/strategy.cpp