MemosTimetabling: src/strategy.cpp File Reference
src/strategy.cpp File Reference
#include "strategy.h"
#include "solver_config.h"
#include "neighbourhood.h"
#include "model.h"
#include "cuts.h"
Functions
int roundProperly (double x)
IloCplex::Callback AnytimeStrategy (IloEnv &env, Model &s, Config &configuration)
IloCplex::Callback ContractStrategy (IloEnv &env, Model &s, Config &configuration)
IloCplex::Callback SolutionSavingStrategy (IloEnv &env, Model &s, Config &configuration)
IloCplex::Callback SolutionPolishingStrategy (IloEnv &env, Model &s, Config &configuration)
Function Documentation
IloCplex::Callback AnytimeStrategy (IloEnv & env, Model & s, Config & configuration)
Definition at line 256 of file strategy.cpp.
{
  return (IloCplex::Callback(new (env) AnytimeStrategyI(env, s, configuration)));
}
IloCplex::Callback ContractStrategy (IloEnv & env, Model & s, Config & configuration)
Definition at line 282 of file strategy.cpp.
{
  return (IloCplex::Callback(new (env) ContractStrategyI(env, s, configuration)));
}
int roundProperly (double x) [inline]
Definition at line 30 of file strategy.cpp.
Referenced by Udine::StrategyI::getFixDayNeighbourhood(), Udine::StrategyI::getFixPeriodNeighbourhood(), Udine::SolutionSavingStrategyI::main(), Udine::StrategyI::sumExtraRoomsUsed(), Udine::StrategyI::sumMissingCourseDays(), Udine::StrategyI::sumMissingSeats(), and Udine::StrategyI::sumSingletonChecks().
{ return int(std::floor(x + 0.5f)); }
IloCplex::Callback SolutionPolishingStrategy (IloEnv & env, Model & s, Config & configuration)
Definition at line 401 of file strategy.cpp.
{
  return (IloCplex::Callback(new (env) SolutionPolishingStrategyI(env, s, configuration)));
}
IloCplex::Callback SolutionSavingStrategy (IloEnv & env, Model & s, Config & configuration)
Definition at line 317 of file strategy.cpp.
{
  return (IloCplex::Callback(new (env) SolutionSavingStrategyI(env, s, configuration)));
}