MemosTimetabling: Udine::Config Struct Reference
Udine::Config Struct Reference
#include <solver_config.h>
Public Member Functions
Config (IloEnv &env, char *pathToInstance, const char *configIdentifier)
time_t elapsed ()
bool getParam (FeatureUse f)
int getFrequency (FeatureUseFrequency f)
int getCount (FeatureUseCount c)
ObjectiveWeights getWeights (ModelType s)
void addSolutionCost (ModelType s, int value)
void apply (IloCplex &cplex, ModelType instance)
Data Fields
const char * path
const char * configId
time_t globalStart
std::vector
< IloCplex::ParameterSet > params
int upperBounds [ModelTypeLen]
bool featureUse [FeatureUseLen]
int featureUseFrequency [FeatureUseFrequencyLen]
int featureUseCount [FeatureUseCountLen]
Strategy strategy
float anytimeDivingOnset [ModelTypeLen]
float contractTimelimit
std::vector< ObjectiveWeights > weights
Detailed Description
Definition at line 107 of file solver_config.h.
Constructor & Destructor Documentation
Config::Config (IloEnv & env, char * pathToInstance, const char * configIdentifier)
Definition at line 27 of file solver_config.cpp.
References anytimeDivingOnset, Udine::ContractAlgorithm, contractTimelimit, Udine::CutsFromPregeneratedCliques, Udine::CutsFromPregeneratedPatterns, Udine::CutsFromTriangles, featureUse, featureUseCount, featureUseFrequency, Udine::FixDayDiveFromSurface, Udine::FixPeriodDiveFromFixDay, Udine::FixPeriodDiveFromSurface, globalStart, Udine::ModelTypeLen, params, strategy, upperBounds, Udine::UseAdditionalVariables, Udine::UseDisaggregation, Udine::UseDynamicCutsAtSurface, Udine::UseHeuristicCompactnessAtSurface, Udine::UseHeuristicCompactnessInDayDives, Udine::UseLowerBoundLogging, Udine::UseLpFilesExport, Udine::UseMRoomAggegation, Udine::UseNeighbourhoodLogging, Udine::UseObjectiveComponents, Udine::UsePreprocessingFriendlyFormulation, Udine::UseRoomSoftfixing, Udine::UseSolutionLogging, Udine::UseSpecialOrderedSets, Udine::UseSpreadOnlyNeighbourhoods, Udine::UseStaticCliqueCutsAtSurface, Udine::UseStaticCliqueCutsInDives, Udine::UseStaticImpliedBounds, Udine::UseStaticPatternEnumeration, Udine::UseZeroRoomStability, and weights.
  : path(pathToInstance),
    configId(configIdentifier) {
  globalStart = std::time(NULL);
  strategy = ContractAlgorithm;
  contractTimelimit = 3600;
  for (int m = 0; m < ModelTypeLen; m++) {
    params.push_back(IloCplex::ParameterSet(env));
    weights.push_back(ObjectiveWeights(1, 5, 2, 1));
    anytimeDivingOnset[m] = 0;
  }
  featureUse[UseSpecialOrderedSets] = false;
  featureUse[UseStaticCliqueCutsAtSurface] = true;
  featureUse[UseStaticCliqueCutsInDives] = true;
  featureUse[UseDisaggregation] = false;
  featureUse[UseStaticImpliedBounds] = true;
  featureUse[UseStaticPatternEnumeration] = false;
  featureUse[UseHeuristicCompactnessAtSurface] = false;
  featureUse[UseHeuristicCompactnessInDayDives] = true;
  featureUse[UseNeighbourhoodLogging] = true;
  featureUse[UseLowerBoundLogging] = true;
  featureUse[UseSolutionLogging] = true;
  featureUse[UseDynamicCutsAtSurface] = false;
  featureUse[UseZeroRoomStability] = false;
  featureUse[UsePreprocessingFriendlyFormulation] = false;
  featureUse[UseAdditionalVariables] = true;
  featureUse[UseLpFilesExport] = false;
  featureUse[UseRoomSoftfixing] = false;
  featureUse[UseMRoomAggegation] = false;
  featureUse[UseSpreadOnlyNeighbourhoods] = false;
  featureUse[UseObjectiveComponents] = true;
  featureUseFrequency[CutsFromPregeneratedCliques] = 5;
  featureUseFrequency[CutsFromPregeneratedPatterns] = 5;
  featureUseFrequency[CutsFromTriangles] = 5;
  featureUseCount[FixDayDiveFromSurface] = 3;
  featureUseCount[FixPeriodDiveFromSurface]= 3;
  featureUseCount[FixPeriodDiveFromFixDay] = 3;
  for (int p = 0; p < ModelTypeLen; p++) {
    params[p].setParam(IloCplex::ObjDif, 1);
    params[p].setParam(IloCplex::WorkMem, 512);
    upperBounds[p] = -1;
  }
}
Member Function Documentation
void Config::addSolutionCost (ModelType s, int value)
Definition at line 102 of file solver_config.cpp.
References Udine::FixDay, Udine::FixPeriod, params, and upperBounds.
Referenced by Udine::SolutionPolishingStrategyI::main(), and Udine::SolutionSavingStrategyI::main().
{
  if ((upperBounds[t] < 0) || (v == std::min(upperBounds[t], v))) {
    upperBounds[t] = v;
    params[t].setParam(IloCplex::CutUp, v - 0.5);
    if (t == FixPeriod && (upperBounds[FixDay] < 0) || (v == std::min(upperBounds[FixDay], v))) {
      upperBounds[FixDay] = v;
      params[FixDay].setParam(IloCplex::CutUp, v - 0.5);
    }
  }
}
void Config::apply (IloCplex & cplex, ModelType instance)
Definition at line 113 of file solver_config.cpp.
References Udine::ModelTypeLen, and params.
Referenced by Udine::StrategyI::runDiver(), and Udine::Solver::Solver().
{
  assert(t >= 0 && t < ModelTypeLen);
  cplex.setParameterSet(params[t]);
}
time_t Config::elapsed ()
Definition at line 98 of file solver_config.cpp.
References globalStart.
Referenced by Udine::ContractStrategyI::finishOff(), Udine::StrategyI::logNeighbrouhood(), Udine::SolutionSavingStrategyI::main(), Udine::AnytimeStrategyI::main(), Udine::BoundSaverI::main(), and Udine::Solver::Solver().
                       {
  return (std::time(NULL) - globalStart);
}
int Config::getCount (FeatureUseCount c)
Definition at line 88 of file solver_config.cpp.
References featureUseCount, and Udine::FeatureUseCountLen.
Referenced by Udine::SolutionPolishingStrategyI::finishOff(), and Udine::ContractStrategyI::finishOff().
{
  assert(c >= 0 && c < FeatureUseCountLen);
  return featureUseCount[c];
}
int Config::getFrequency (FeatureUseFrequency f)
Definition at line 83 of file solver_config.cpp.
References featureUseFrequency, and Udine::FeatureUseFrequencyLen.
Referenced by Udine::CutManagerI::main().
{
  assert(f >= 0 && f < FeatureUseFrequencyLen);
  return featureUseFrequency[f];
}
bool Config::getParam (FeatureUse f)
Definition at line 78 of file solver_config.cpp.
References featureUse, and Udine::FeatureUseLen.
Referenced by Udine::Model::generateCompactness(), Udine::Model::generateCoursePeriods(), Udine::Model::generateHardConstraints(), Udine::Model::generateMinCourseDays(), Udine::Model::generateNeighbourhood(), Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), Udine::Model::generateRoomStability(), Udine::StrategyI::logNeighbrouhood(), Udine::CutManagerI::main(), Udine::Model::Model(), Udine::StrategyI::runDiver(), Udine::Solver::Solver(), Udine::StrategyI::sumSingletonChecks(), and Udine::Variables::Variables().
{
  assert(f >= 0 && f < FeatureUseLen);
  return featureUse[f];
}
ObjectiveWeights Config::getWeights (ModelType s)
Definition at line 93 of file solver_config.cpp.
References Udine::ModelTypeLen, and weights.
Referenced by Udine::Model::generateObjective(), Udine::Model::generateObjectiveComponents(), and Udine::SolutionSavingStrategyI::main().
{
  assert(t >= 0 && t < ModelTypeLen);
  return weights[t];
}
Field Documentation
float Udine::Config::anytimeDivingOnset[ModelTypeLen]
Definition at line 126 of file solver_config.h.
Referenced by Config(), and Udine::AnytimeStrategyI::main().
const char* Udine::Config::configId
Definition at line 111 of file solver_config.h.
Referenced by Udine::Solver::Solver().
float Udine::Config::contractTimelimit
Definition at line 127 of file solver_config.h.
Referenced by Config(), and Udine::ContractStrategyI::finishOff().
bool Udine::Config::featureUse[FeatureUseLen]
Definition at line 119 of file solver_config.h.
Referenced by Config(), and getParam().
int Udine::Config::featureUseCount[FeatureUseCountLen]
Definition at line 121 of file solver_config.h.
Referenced by Config(), and getCount().
int Udine::Config::featureUseFrequency[FeatureUseFrequencyLen]
Definition at line 120 of file solver_config.h.
Referenced by Config(), and getFrequency().
time_t Udine::Config::globalStart
Definition at line 112 of file solver_config.h.
Referenced by Config(), and elapsed().
std::vector<IloCplex::ParameterSet> Udine::Config::params
Definition at line 115 of file solver_config.h.
Referenced by addSolutionCost(), apply(), and Config().
const char* Udine::Config::path
Definition at line 110 of file solver_config.h.
Referenced by Udine::StrategyI::logNeighbrouhood(), Udine::SolutionSavingStrategyI::main(), Udine::StrategyI::runDiver(), and Udine::Solver::Solver().
Strategy Udine::Config::strategy
Definition at line 123 of file solver_config.h.
Referenced by Config(), and Udine::Solver::Solver().
int Udine::Config::upperBounds[ModelTypeLen]
Definition at line 116 of file solver_config.h.
Referenced by addSolutionCost(), and Config().
std::vector<ObjectiveWeights> Udine::Config::weights
Definition at line 130 of file solver_config.h.
Referenced by Config(), and getWeights().
The documentation for this struct was generated from the following files:
src/solver_config.h
src/solver_config.cpp